import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Award, Star } from 'lucide-react';
import { Card } from '../components/ui/Card';
import { ProgressBar } from '../components/ui/ProgressBar';
import { Badge } from '../components/ui/Badge';
import { achievements, missions, profile, skills } from '../lib/mockData';
export function Profile() {
    const xpProgress = Math.round((profile.xp / profile.nextLevel) * 100);
    return (_jsxs("div", { className: "space-y-6", children: [_jsx(Card, { className: "p-7", children: _jsxs("div", { className: "flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "grid h-20 w-20 place-items-center rounded-[1.5rem] bg-[linear-gradient(135deg,#6c63ff,#a855f7)] text-2xl font-black text-white shadow-[0_16px_36px_rgba(108,99,255,0.3)]", children: "LS" }), _jsxs("div", { children: [_jsx("p", { className: "section-kicker", children: "dev.profile" }), _jsx("h2", { className: "mt-3 text-3xl font-extrabold tracking-[-0.04em] text-textPrimary", children: profile.name }), _jsx("p", { className: "mt-2 text-textSecondary", children: profile.title }), _jsxs("div", { className: "mt-4 flex flex-wrap gap-2", children: [_jsxs(Badge, { tone: "warning", children: [profile.xp, " XP"] }), _jsxs(Badge, { tone: "info", children: ["#", profile.ranking] })] })] })] }), _jsxs("div", { className: "w-full max-w-md rounded-[1.25rem] border border-white/8 bg-white/[0.03] p-5", children: [_jsxs("div", { className: "mb-3 flex justify-between text-sm", children: [_jsxs("span", { className: "font-semibold text-textPrimary", children: ["Level ", profile.level] }), _jsxs("span", { className: "font-mono text-textSecondary", children: [profile.xp, " XP"] })] }), _jsx(ProgressBar, { value: xpProgress }), _jsxs("p", { className: "mt-3 text-sm text-textSecondary", children: [profile.nextLevel - profile.xp, " XP restantes para o pr\u00F3ximo n\u00EDvel"] })] })] }) }), _jsx("div", { className: "grid gap-4 md:grid-cols-5", children: [
                    ['Quizzes', profile.quizzes],
                    ['Precisão', `${profile.accuracy}%`],
                    ['Sequência', `${profile.streak} dias`],
                    ['Melhor categoria', profile.bestCategory],
                    ['Ranking', `#${profile.ranking}`],
                ].map(([label, value]) => (_jsxs(Card, { className: "p-5", children: [_jsx("p", { className: "font-mono text-3xl font-extrabold text-textPrimary", children: value }), _jsx("p", { className: "mt-2 text-sm text-textSecondary", children: label })] }, label))) }), _jsxs("div", { className: "grid gap-6 2xl:grid-cols-2", children: [_jsxs(Card, { className: "p-6", children: [_jsxs("div", { className: "mb-5 flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-xl font-bold tracking-[-0.03em] text-textPrimary", children: "Mapa de habilidades" }), _jsx("p", { className: "mt-2 text-sm text-textSecondary", children: "Distribui\u00E7\u00E3o por categoria com leitura r\u00E1pida de dom\u00EDnio." })] }), _jsx(Badge, { children: "Mastery" })] }), _jsx("div", { className: "space-y-4", children: skills.map((skill) => _jsx(SkillRow, { category: skill.category, mastery: skill.mastery }, skill.category)) })] }), _jsxs(Card, { className: "p-6", children: [_jsxs("div", { className: "mb-5 flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-xl font-bold tracking-[-0.03em] text-textPrimary", children: "Miss\u00F5es ativas" }), _jsx("p", { className: "mt-2 text-sm text-textSecondary", children: "Pequenos marcos para manter cad\u00EAncia di\u00E1ria." })] }), _jsx(Badge, { tone: "success", children: "Daily" })] }), _jsx("div", { className: "space-y-3", children: missions.map((mission) => (_jsxs("div", { className: "rounded-[1.25rem] border border-white/8 bg-white/[0.03] p-4", children: [_jsxs("div", { className: "mb-2 flex items-center justify-between", children: [_jsx("span", { className: "text-sm font-semibold text-textPrimary", children: mission.title }), _jsxs("span", { className: "font-mono text-xs text-success", children: ["+", mission.xp] })] }), _jsx(ProgressBar, { value: (mission.progress / mission.target) * 100 })] }, mission.title))) })] })] }), _jsxs(Card, { className: "p-6", children: [_jsxs("div", { className: "mb-5 flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-xl font-bold tracking-[-0.03em] text-textPrimary", children: "Medalhas e t\u00EDtulos" }), _jsx("p", { className: "mt-2 text-sm text-textSecondary", children: "Reconhecimento visual para evolu\u00E7\u00E3o consistente." })] }), _jsx(Badge, { tone: "info", children: "Collection" })] }), _jsx("div", { className: "grid gap-4 lg:grid-cols-4", children: achievements.map(([name, status]) => (_jsxs("div", { className: "rounded-[1.25rem] border border-white/8 bg-white/[0.03] p-4", children: [_jsx("div", { className: "mb-4 grid h-10 w-10 place-items-center rounded-2xl bg-primary/12 text-primary", children: _jsx(Award, { size: 18 }) }), _jsx("p", { className: "font-semibold text-textPrimary", children: name }), _jsx("p", { className: "mt-2 text-sm text-textSecondary", children: status })] }, name))) })] })] }));
}
function SkillRow({ category, mastery }) {
    return (_jsxs("div", { children: [_jsxs("div", { className: "mb-2 flex items-center justify-between text-sm", children: [_jsxs("span", { className: "flex items-center gap-2 font-semibold text-textPrimary", children: [_jsx(Star, { size: 15, className: "text-warning" }), category] }), _jsxs("span", { className: "font-mono text-textSecondary", children: [mastery, "%"] })] }), _jsx(ProgressBar, { value: mastery })] }));
}
